### ISSUE TITLE
Inventory bug

### ISSUE THREAD

**Issue by Xofter** [Xephi/AuthMeReloaded#203]
Inventory wipe after MC crash or internet DC. Protect inventory config fixes this however it can let you eat other food/op apples and other small bugs. Please fix this as soon as possible (because people are eating other peoples food n so on)

**Comment by sgdc3** [comment]
protect inventory is the feature that blocks inventory abused, the only bug is the protect inventory malfunction!

**Comment by Xofter** [comment]
yes i know this, thats why i would like the inventory wipe bug to be fixed ;>

**Comment by sgdc3** [comment]
Lol. Tomorrow I will look into the issue ;)

**Comment by sgdc3** [comment]
@Xofter Should have been fixed! Check this version: http://ci.xephi.fr/job/DEVBUILD-ONLY/lastSuccessfulBuild/artifact/target/AuthMe-5.0-SNAPSHOT.jar

**Comment by Xofter** [comment]
You did not fix anything, just made a lot of new errors and unsuccesfulbuild [23:33:49] [Craft Scheduler Thread - 12/WARN]: [AuthMe] Error with the login translation, verify in your ./plugins/AuthMe/messages/messages_en.yml !
[23:33:49] [Craft Scheduler Thread - 12/INFO]: [AuthMe] sapokelis logged in!
[23:33:49] [Craft Scheduler Thread - 17/WARN]: [AuthMe] Error with the login translation, verify in your ./plugins/AuthMe/messages/messages_en.yml !
[23:33:49] [Craft Scheduler Thread - 17/INFO]: [AuthMe] HDSniperis logged in!
[23:33:49] [Craft Scheduler Thread - 12/WARN]: [AuthMe] Error with the login translation, verify in your ./plugins/AuthMe/messages/messages_en.yml !
[23:33:49] [Craft Scheduler Thread - 12/INFO]: [AuthMe] Spyder638 logged in!
[23:33:50] [Thread-45/INFO]: UUID of player _Banned_ is 1f5017ff-0216-38fc-b7b1-0cbebd9ece8c
[23:33:50] [Server thread/INFO]: _Banned_[/80.212.139.37:16352] logged in with entity id 1541 at ([Pasaulis]210.691311057657, 72.0, -1010.3470458608143)
[23:33:50] [Craft Scheduler Thread - 17/WARN]: [AuthMe] Error with the login_msg translation, verify in your ./plugins/AuthMe/messages/messages_en.yml !
[23:33:50] [Async Chat Thread - #0/INFO]: <HDSniperis> s
[23:33:50] [Async Chat Thread - #0/INFO]: [m(**Leavines[0;37;1m [0;31;22m[[0;31;1mDumbuldoras[0;31;22m] [0;32;22m[21m[[0;32;1m[21mElite[0;32;22m[21m][0;32;22m HDSniperis[m) s[m
[23:33:50] [Craft Scheduler Thread - 1/WARN]: [AuthMe] Error with the login translation, verify in your ./plugins/AuthMe/messages/messages_en.yml !
[23:33:50] [Craft Scheduler Thread - 1/INFO]: [AuthMe] MRmuse logged in!
[23:33:51] [Thread-47/INFO]: UUID of player GetRekt is 1791e368-8c39-346e-981f-e51aeb416f29
[23:33:51] [Server thread/INFO]: GetRekt[/62.80.239.132:57456] logged in with entity id 1663 at ([Pasaulis]168.5, 78.0, -964.5)
[23:33:51] [Craft Scheduler Thread - 10/WARN]: java.lang.NullPointerException
[23:33:51] [Craft Scheduler Thread - 10/WARN]: 	at fr.xephi.authme.cache.backup.JsonCache$PlayerDataDeserializer.deserialize(JsonCache.java:145)
[23:33:51] [Craft Scheduler Thread - 10/WARN]: 	at fr.xephi.authme.cache.backup.JsonCache$PlayerDataDeserializer.deserialize(JsonCache.java:141)
[23:33:51] [Craft Scheduler Thread - 10/WARN]: 	at com.google.gson.TreeTypeAdapter.read(TreeTypeAdapter.java:58)
[23:33:51] [Craft Scheduler Thread - 10/WARN]: 	at com.google.gson.Gson.fromJson(Gson.java:803)
[23:33:51] [Craft Scheduler Thread - 10/WARN]: 	at com.google.gson.Gson.fromJson(Gson.java:768)
[23:33:51] [Craft Scheduler Thread - 10/WARN]: 	at com.google.gson.Gson.fromJson(Gson.java:717)
[23:33:51] [Craft Scheduler Thread - 10/WARN]: 	at com.google.gson.Gson.fromJson(Gson.java:689)
[23:33:51] [Craft Scheduler Thread - 10/WARN]: 	at fr.xephi.authme.cache.backup.JsonCache.readCache(JsonCache.java:82)
[23:33:51] [Craft Scheduler Thread - 10/WARN]: 	at fr.xephi.authme.events.StoreInventoryEvent.<init>(StoreInventoryEvent.java:27)
[23:33:51] [Craft Scheduler Thread - 10/WARN]: 	at fr.xephi.authme.cache.limbo.LimboCache.addLimboPlayer(LimboCache.java:42)
[23:33:51] [Craft Scheduler Thread - 10/WARN]: 	at fr.xephi.authme.cache.limbo.LimboCache.updateLimboPlayer(LimboCache.java:126)
[23:33:51] [Craft Scheduler Thread - 10/WARN]: 	at fr.xephi.authme.process.join.AsyncronousJoin.process(AsyncronousJoin.java:134)
[23:33:51] [Craft Scheduler Thread - 10/WARN]: 	at fr.xephi.authme.process.Management$5.run(Management.java:81)
[23:33:51] [Craft Scheduler Thread - 10/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
[23:33:51] [Craft Scheduler Thread - 10/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[23:33:51] [Craft Scheduler Thread - 10/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[23:33:51] [Craft Scheduler Thread - 10/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[23:33:51] [Craft Scheduler Thread - 10/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[23:33:51] [Craft Scheduler Thread - 10/WARN]: java.lang.NullPointerException
[23:33:51] [Craft Scheduler Thread - 10/WARN]: 	at fr.xephi.authme.cache.backup.JsonCache$PlayerDataDeserializer.deserialize(JsonCache.java:145)
[23:33:51] [Craft Scheduler Thread - 10/WARN]: 	at fr.xephi.authme.cache.backup.JsonCache$PlayerDataDeserializer.deserialize(JsonCache.java:141)
[23:33:51] [Craft Scheduler Thread - 10/WARN]: 	at com.google.gson.TreeTypeAdapter.read(TreeTypeAdapter.java:58)
[23:33:51] [Craft Scheduler Thread - 10/WARN]: 	at com.google.gson.Gson.fromJson(Gson.java:803)
[23:33:51] [Craft Scheduler Thread - 10/WARN]: 	at com.google.gson.Gson.fromJson(Gson.java:768)
[23:33:51] [Craft Scheduler Thread - 10/WARN]: 	at com.google.gson.Gson.fromJson(Gson.java:717)
[23:33:51] [Craft Scheduler Thread - 10/WARN]: 	at com.google.gson.Gson.fromJson(Gson.java:689)
[23:33:51] [Craft Scheduler Thread - 10/WARN]: 	at fr.xephi.authme.cache.backup.JsonCache.readCache(JsonCache.java:82)
[23:33:51] [Craft Scheduler Thread - 10/WARN]: 	at fr.xephi.authme.cache.limbo.LimboCache.addLimboPlayer(LimboCache.java:51)
[23:33:51] [Craft Scheduler Thread - 10/WARN]: 	at fr.xephi.authme.cache.limbo.LimboCache.updateLimboPlayer(LimboCache.java:126)
[23:33:51] [Craft Scheduler Thread - 10/WARN]: 	at fr.xephi.authme.process.join.AsyncronousJoin.process(AsyncronousJoin.java:134)
[23:33:51] [Craft Scheduler Thread - 10/WARN]: 	at fr.xephi.authme.process.Management$5.run(Management.java:81)
[23:33:51] [Craft Scheduler Thread - 10/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
[23:33:51] [Craft Scheduler Thread - 10/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[23:33:51] [Craft Scheduler Thread - 10/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[23:33:51] [Craft Scheduler Thread - 10/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[23:33:51] [Craft Scheduler Thread - 10/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[23:33:51] [Craft Scheduler Thread - 10/WARN]: [AuthMe] Error with the login_msg translation, verify in your ./plugins/AuthMe/messages/messages_en.yml !
[23:33:53] [Craft Scheduler Thread - 1/INFO]: [AuthMe] antispide used the wrong password
[23:33:53] [Async Chat Thread - #0/WARN]: [AuthMe] Error with the login_msg translation, verify in your ./plugins/AuthMe/messages/messages_en.yml !
[23:33:53] [Server thread/WARN]: [AuthMe] Error with the wrong_pwd translation, verify in your ./plugins/AuthMe/messages/messages_en.yml !
[23:33:53] [Server thread/INFO]: [Heroes] Saved hero: antispide
[23:33:53] [Server thread/WARN]: handleDisconnection() called twice
[23:33:54] [Server thread/INFO]: [Heroes] Saved hero: Xofter
[23:33:56] [Thread-51/INFO]: UUID of player antispide is 2ad4f65b-d9e6-3aee-a772-880ce7f7b86d
[23:33:56] [Server thread/INFO]: antispide[/86.100.224.143:49370] logged in with entity id 1800 at ([Pasaulis]168.5, 78.0, -964.5)
[23:33:56] [Craft Scheduler Thread - 6/WARN]: java.lang.NullPointerException
[23:33:56] [Craft Scheduler Thread - 6/WARN]: 	at fr.xephi.authme.cache.backup.JsonCache$PlayerDataDeserializer.deserialize(JsonCache.java:145)
[23:33:56] [Craft Scheduler Thread - 6/WARN]: 	at fr.xephi.authme.cache.backup.JsonCache$PlayerDataDeserializer.deserialize(JsonCache.java:141)
[23:33:56] [Craft Scheduler Thread - 6/WARN]: 	at com.google.gson.TreeTypeAdapter.read(TreeTypeAdapter.java:58)
[23:33:56] [Craft Scheduler Thread - 6/WARN]: 	at com.google.gson.Gson.fromJson(Gson.java:803)
[23:33:56] [Craft Scheduler Thread - 6/WARN]: 	at com.google.gson.Gson.fromJson(Gson.java:768)
[23:33:56] [Craft Scheduler Thread - 6/WARN]: 	at com.google.gson.Gson.fromJson(Gson.java:717)
[23:33:56] [Craft Scheduler Thread - 6/WARN]: 	at com.google.gson.Gson.fromJson(Gson.java:689)
[23:33:56] [Craft Scheduler Thread - 6/WARN]: 	at fr.xephi.authme.cache.backup.JsonCache.readCache(JsonCache.java:82)
[23:33:56] [Craft Scheduler Thread - 6/WARN]: 	at fr.xephi.authme.events.StoreInventoryEvent.<init>(StoreInventoryEvent.java:27)
[23:33:56] [Craft Scheduler Thread - 6/WARN]: 	at fr.xephi.authme.cache.limbo.LimboCache.addLimboPlayer(LimboCache.java:42)
[23:33:56] [Craft Scheduler Thread - 6/WARN]: 	at fr.xephi.authme.cache.limbo.LimboCache.updateLimboPlayer(LimboCache.java:126)
[23:33:56] [Craft Scheduler Thread - 6/WARN]: 	at fr.xephi.authme.process.join.AsyncronousJoin.process(AsyncronousJoin.java:134)
[23:33:56] [Craft Scheduler Thread - 6/WARN]: 	at fr.xephi.authme.process.Management$5.run(Management.java:81)
[23:33:56] [Craft Scheduler Thread - 6/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
[23:33:56] [Craft Scheduler Thread - 6/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[23:33:56] [Craft Scheduler Thread - 6/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[23:33:56] [Craft Scheduler Thread - 6/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[23:33:56] [Craft Scheduler Thread - 6/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[23:33:56] [Craft Scheduler Thread - 6/WARN]: java.lang.NullPointerException
[23:33:56] [Craft Scheduler Thread - 6/WARN]: 	at fr.xephi.authme.cache.backup.JsonCache$PlayerDataDeserializer.deserialize(JsonCache.java:145)
[23:33:56] [Craft Scheduler Thread - 6/WARN]: 	at fr.xephi.authme.cache.backup.JsonCache$PlayerDataDeserializer.deserialize(JsonCache.java:141)
[23:33:56] [Craft Scheduler Thread - 6/WARN]: 	at com.google.gson.TreeTypeAdapter.read(TreeTypeAdapter.java:58)
[23:33:56] [Craft Scheduler Thread - 6/WARN]: 	at com.google.gson.Gson.fromJson(Gson.java:803)
[23:33:56] [Craft Scheduler Thread - 6/WARN]: 	at com.google.gson.Gson.fromJson(Gson.java:768)
[23:33:56] [Craft Scheduler Thread - 6/WARN]: 	at com.google.gson.Gson.fromJson(Gson.java:717)
[23:33:56] [Craft Scheduler Thread - 6/WARN]: 	at com.google.gson.Gson.fromJson(Gson.java:689)
[23:33:56] [Craft Scheduler Thread - 6/WARN]: 	at fr.xephi.authme.cache.backup.JsonCache.readCache(JsonCache.java:82)
[23:33:56] [Craft Scheduler Thread - 6/WARN]: 	at fr.xephi.authme.cache.limbo.LimboCache.addLimboPlayer(LimboCache.java:51)
[23:33:56] [Craft Scheduler Thread - 6/WARN]: 	at fr.xephi.authme.cache.limbo.LimboCache.updateLimboPlayer(LimboCache.java:126)
[23:33:56] [Craft Scheduler Thread - 6/WARN]: 	at fr.xephi.authme.process.join.AsyncronousJoin.process(AsyncronousJoin.java:134)
[23:33:56] [Craft Scheduler Thread - 6/WARN]: 	at fr.xephi.authme.process.Management$5.run(Management.java:81)
[23:33:56] [Craft Scheduler Thread - 6/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
[23:33:56] [Craft Scheduler Thread - 6/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[23:33:56] [Craft Scheduler Thread - 6/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[23:33:56] [Craft Scheduler Thread - 6/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[23:33:56] [Craft Scheduler Thread - 6/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[23:33:56] [Craft Scheduler Thread - 6/WARN]: [AuthMe] Error with the login_msg translation, verify in your ./plugins/AuthMe/messages/messages_en.yml !
[23:33:56] [Craft Scheduler Thread - 10/WARN]: [AuthMe] Error with the login translation, verify in your ./plugins/AuthMe/messages/messages_en.yml !
[23:33:56] [Craft Scheduler Thread - 10/INFO]: [AuthMe] EDNAT logged in!
[23:33:57] [Craft Scheduler Thread - 17/WARN]: [AuthMe] Error with the login translation, verify in your ./plugins/AuthMe/messages/messages_en.yml !
[23:33:57] [Craft Scheduler Thread - 17/INFO]: [AuthMe] _Banned_ logged in!

**Comment by sgdc3** [comment]
try new version: http://ci.xephi.fr/job/DEVBUILD-ONLY/lastSuccessfulBuild/artifact/target/AuthMe-5.0-SNAPSHOT.jar

**Comment by sgdc3** [comment]
sorry but it's hard to work with only 1 developer

**Comment by Xofter** [comment]
dude you could try it on your own computer, i own a big network i cant restart the server every hour or so

**Comment by sgdc3** [comment]
I cant test it with a single player -_-

**Comment by Xofter** [comment]
Still getting errors, and errors with traslation/message or something

**Comment by sgdc3** [comment]
@Xofter Fixed! Can you try latest dev build and close the issue? :)
