### ISSUE TITLE
Table Upload

### ISSUE THREAD

**Issue by emre24807** [Xephi/AuthMeReloaded#226]
(Sorry for my bad english)
I am using website registration system. When my members registered at website, their datas are entered the authme table. But plugin don't update table. So my members can't login server until server is restarted.

**Comment by sgdc3** [comment]
@DNx5 @games647 What do you think about this?

**Comment by DNx5** [comment]
What type of database and website?

**Comment by Xephi** [comment]
I think it's due to MySQL cache system :/

**Comment by Xephi** [comment]
@emre24807 can you please try with latest build ?

**Comment by sgdc3** [comment]
Should have been fixed @emre24807

**Comment by sgdc3** [comment]
@Xephi we can close this

**Comment by DNx5** [comment]
Xephi only disabled the MySQL internal cache, but the authme itself doesn't update the registered users list if cache is enabled in config. So, I think it's not fixed.

**Comment by sgdc3** [comment]
@emre24807 should have been fixed! ;)

**Comment by sgdc3** [comment]
no answer
