### ISSUE TITLE
AuthMe Login Message

### ISSUE THREAD

**Issue by kingpyro** [Xephi/AuthMeReloaded#248]
So on a vanilla server when someone logs in the server say "so and so has logged in.". Before on the old version (3.2), authme wouldn't let that message go through until after someone /login 's. Is it possible to re-implement this feature? Just because it gets misleading on a cracked server if someone logs in as someone else and it says so and so logs in. But they never pass the authentication screen. 

Same with the logout message, there wouldn't be a need to show that message unless someone was authenticated.

**Comment by sgdc3** [comment]
Done :) try latest -Dev build!

**Comment by kingpyro** [comment]
Still same thing.
![still persists](https://cloud.githubusercontent.com/assets/1954074/10869690/aa2db004-8084-11e5-9b3a-fe4886d4ee8f.PNG)

**Comment by sgdc3** [comment]
you need to enable an option: delayjoinleavemessages

**Comment by sgdc3** [comment]
@kingpyro

**Comment by kingpyro** [comment]
delayJoinLeaveMessages: true

Default set to true.

**Comment by Xephi** [comment]
Nop, we can't set it at default, cause it change the default rendering of informations, and we don't want it to become a "Magic"  cause of some reports :)

**Comment by kingpyro** [comment]
I didn't mean to set it as default true. It came into my config like that already.

**Comment by Xephi** [comment]
Oh ok, I will take a look at your problem :')

**Comment by kingpyro** [comment]
Thanks @Xephi

**Comment by kingpyro** [comment]
@Xephi any update on this? We had someone constantly joining and leaving and it was spamming the chat with login messages. Even on build 181, the delayJoinLeaveMessages still doesn't work.

**Comment by sgdc3** [comment]
@kingpyro fixed

**Comment by sgdc3** [comment]
@kingpyro should have been fixed

**Comment by kingpyro** [comment]
Sorry for the late response. Not fixed.

I even tried regenerating an using the default config. (Which makes the delayJoinLeaveMessages as true). I tried with false just in case if the Boolean was switched, no success.

@sgdc3 https://i.imgur.com/xFDoITm.png

**Comment by kingpyro** [comment]
Build 682 btw.

**Comment by sgdc3** [comment]
What's your plugin list?

**Comment by sgdc3** [comment]
@kingpyro bump

**Comment by kingpyro** [comment]
@sgdc3  Nothing, I every dev build you send out and I respond on is newest spigot and most recent dev of authme.

**Comment by sgdc3** [comment]
@DNx5 Can you check this out please? ;)

**Comment by sgdc3** [comment]
@games647 do you have any ideas about the cause of this? :/

**Comment by games647** [comment]
Looks like the settings are not loaded correctly.

**Comment by sgdc3** [comment]
@kingpyro

**Comment by kingpyro** [comment]
Works!

*successfull cheer and super happy smile on face*

Hahaha, thank you very much guys for your hard work and dedication! :)

**Comment by sgdc3** [comment]
You're welcome. ;)

**Comment by sgdc3** [comment]
Whoops sorry  @DNx5  ;)
