### ISSUE TITLE
Moderator chat spying (Compatibility issue with FactionChat plugin)

### ISSUE THREAD

**Issue by MithrandirCraft** [Xephi/AuthMeReloaded#259]
Steps for reproducing this problem:

1.Install a blank Spigot server
2.Install Authme's latest version, Factions, FactionChat & Mcore plugins.
3.Give faction chat permissions to two player names for moderator chat usage: "factionChat.modChat"
4.Log in with one of those names, and constantly spam the moderator chat.
5.Enter the server with the other name, without logging in.

Issue:

The second player name should not be capable of reading the moderator chat untill he has logged in. Instead he can read everything for 60 seconds and then log back in to keep on reading lol.

Edit: Current situation:

Moderator chat doesn't work at all.

----------------------------------------------------------

Current authme version: 5.2-SNAPSHOT-b660
Faction chat version: 1.9.12-SNAPSHOT
Current Minecraft-Spigot version: 1.8.8

----------------------------------------------------------
Original Bukkit Ticket (Outdated but commented on): 
http://dev.bukkit.org/bukkit-plugins/authme-reloaded/tickets/979-moderator-chat-spying-compat-issue/#comments

**Comment by sgdc3** [comment]
We need just to recompile FactionsChat

**Comment by sgdc3** [comment]
FactionsChat's developer is inactive, we can't do nothing to fix this.

**Comment by MithrandirCraft** [comment]
His last connection was 19 hours ago

http://dev.bukkit.org/bukkit-plugins/factionchat/

His project isn't abandoned.

How about just blocking chat reading untill the user logs in? That would solve any issues with Faction Chat, and any other private chat system (To which I could switch if FactionChat dies).

Would that be possible?

**Comment by Xephi** [comment]
FactionChat use some permission to allow moderator chat reading, isn't it ? Also remove it to unlogged players :O

**Comment by MithrandirCraft** [comment]
Authme config:
----------------------------------------
unLoggedinGroup: prelogin

PEX permissions:
---------------------------------------
groups:
  prelogin:
    permissions:
    - -factionChat.*


It's no use, does this feature work properly? Am I doing something wrong?

**Comment by sgdc3** [comment]
Pex + negative permission nodes = Nope :P
Pex neg nodes are broken in latest versions.

**Comment by MithrandirCraft** [comment]
What? I always thought they worked, but other negative perms seem to be working :S, I was actually taught this function by a PEX dev.

In any case, if I can't negate a permission, what can I do?

I will try:

    permissions: []

Assuming faction chat permissions are off by default.

**Comment by sgdc3** [comment]
Should have been fixed, can you check latest dev build?

**Comment by MithrandirCraft** [comment]
Still not fixed.
![screenshot_1](https://cloud.githubusercontent.com/assets/6623704/11407508/9778a436-93b3-11e5-8f13-e6b780e5053f.png)

**Comment by sgdc3** [comment]
Custom fchat build: http://ci.xephi.fr/job/FactionsChat-AuthMeFix/

**Comment by sgdc3** [comment]
@MithrandirCraft

**Comment by MithrandirCraft** [comment]
Did you actually modify the Faction Chat plugin?

Just tried it, commands don't work.

**Comment by sgdc3** [comment]
Any error?
Is the plugin correctly loaded?

**Comment by MithrandirCraft** [comment]
@sgdc3 The plugin shows up as green "loaded" on /plugins list.

However, there are some errors which I think have to do with this issue:

http://hastebin.com/cibusewafa.avrasm
http://hastebin.com/imoxiwajem.avrasm

**Comment by MithrandirCraft** [comment]
By the way, the current situation with this issue is that right now, using Authme Reloaded + the last official version of FactionChat, moderator chat doesn't work.

**Comment by sgdc3** [comment]
even if logged in

**Comment by MithrandirCraft** [comment]
it seems you have stopped the visualization and usage of that chat all together xD both when logged in and logged out.

**Comment by sgdc3** [comment]
ah, right. Fchat author needs to recompile the plugin

**Comment by sgdc3** [comment]
and remove any authme hook

**Comment by sgdc3** [comment]
not an authme issue anymore

**Comment by MithrandirCraft** [comment]
Ok, the moderator chat is back again, but it can still be read when logged out: /logout

**Comment by MithrandirCraft** [comment]
https://github.com/James137137/FactionChat/issues/12#event-504269111

**Comment by MithrandirCraft** [comment]
Still readable.

**Comment by MithrandirCraft** [comment]
Updated affected versions of both plugins.

**Comment by Xephi** [comment]
https://github.com/James137137/FactionChat/pull/14

I've directly pull request him with the fix

**Comment by MithrandirCraft** [comment]
Fixed with the suspicious FactionChat build that Xephi handed to me.

**Comment by Xephi** [comment]
LOL , it's just a build with the pull request i've send to the dev of FactionChat ;)

**Comment by MithrandirCraft** [comment]
I know, I'm just joking xD
