### ISSUE TITLE
Server hack with authme.player.*

### ISSUE THREAD

**Issue by Dimatert9** [Xephi/AuthMeReloaded#573]
1) Set in default groups permission authme.player.*
2) Join to server, login.
3) Login to server with other account, dont login.
4) write from 1st client. /authme forcelogin Name_2nd_acc

**Comment by Dimatert9** [comment]
#562

**Comment by games647** [comment]
Which build do you have?

**Comment by Dimatert9** [comment]
654
from CircleCi commit "Update dependencies"

**Comment by sgdc3** [comment]
@Dimatert9 Should have been fixed ;)

**Comment by Dimatert9** [comment]
thakns. its work

**Comment by Dimatert9** [comment]
And fix http://ci.xephi.fr/job/AuthMeReloaded/ in latest version not fixed.
But version from CircleCI is fixed.

**Comment by ljacqu** [comment]
Jenkins (the link you shared) currently has trouble building so the latest changes aren't included just yet. Thanks a lot for mentioning it, though, and thank you for the feedback :)
