### ISSUE TITLE
Hidden inventory

### ISSUE THREAD

**Issue by NewBestX** [Xephi/AuthMeReloaded#818]
Hi!
I have a server selector plugin, that gives everyone a compass every time they go to the Hub world (I am not using bungee, I have multiple worlds and all the selector does is teleport the players to a specific world). I have noticed that if I have `ProtectInventoryBeforeLogIn: true` when the player registers he will have the compass, but will remain hidden until he clicks with his first inventory slot selected (where the compass is).

I tried setting `ProtectInventoryBeforeLogIn: false`, but then the inventory will still be hidden when he types the login command, and afterwards it will remain hidden until the player clicks with the compass.

It works with any item, but with items that do not trigger a special command (like my compass does), you need to open inventory and manually click each slot to reveal the item.

I taught that perhaps it is some incompatibility with the selector plugin, but I added a command to be executed as console after register that gives the player an item, and still no luck.

So, `ProtectInventoryBeforeLogIn: true` - it works with login, won't revel the items with register.
`ProtectInventoryBeforeLogIn: false` - it still hides the items and won't reveal them at all.

Using Spigot 1.10, tested with AuthMe 5.2 Beta3 and with build #1173. Using ProtocolLib Build #300 (4.0.2)

**Comment by sgdc3** [comment]
@NewBestX Could you try latest dev build? It should have been fixed a week ago ;)

**Comment by NewBestX** [comment]
The bug is still here.
`ProtectInventoryBeforeLogIn: true` still won't show the items I had before /register.
After some more research, it looks like if I set the command that gives me an item, I will get it first time I register, but if I do an /unregister, disconnect, than /register again, the problem is back. The command is still executed, but the item remains hidden.
If I register, unregister, disconnect, restart the server and register again it works.

`ProtectInventoryBeforeLogIn: false` works. Looks like there is a problem when changing it to false and doing just an /authme reload ... This is the way I tried last time... Is sort of mixes with the true setting and requires a server restart to fully change.

I did this second research on a local server, I can't restart the main server many times now because there are players online. I will try it in 2- 3 hours, when the players are gone. I will be back with the results from that test, if it is any different.

I have also found a bug with /unregister from another world, but I will create a separate ticket for that one.

**Comment by games647** [comment]
>/authme reload ... This is the way I tried last time... Is sort of mixes with the true setting and requires a server restart to fully change.

So the bug only occurred on authme reload **not on restart**?

**Comment by NewBestX** [comment]
Yes, if ProtectInventoryBeforeLogIn was set to true, changed in config.yml to false then executed the command /authme reload , it would bug, hiding the entire inventory before as well as after login.
If the server is restarted, things seem to be working fine.

**Comment by sgdc3** [comment]
@NewBestX

**Comment by NewBestX** [comment]
Sorry for the late reply.
I see that you tried to fix the /authme reload command when changing `ProtectInventoryBeforeLogIn` from true to false in build #1181. Unfortunately it doesn't work. Perhaps I should recap the steps to reproduce the problem: I started the server with `ProtectInventoryBeforeLogIn: true` in authme config. I join the server and login. I open the config and change the setting to false. Now on the server I do /authme reload and disconnect. Now when I join the inventory will be protected (items invisible), I login and the items remain invisible.
What I think you tried was revealing the items to a secondary player that joined the server BUT haven't yet logged in when /authme reload is executed. I tried this as well, but it doesn't work.

I have also noticed something about the issue I reported in my second post. I have the following setting in the config:
`    forceRegisterCommandsAsConsole:
    - 'clearinventory %p'
    - 'give %p 345 1 name:&e&lServer_Selector'
    - 'broadcast asdasdssdadf'`
* I am using essentials to make things easy, and the broadcast is there to make sure the set of commands was executed.
I have noticed that doing /register ; /unregister ; disconnecting and /register again won't reproduce the bug anymore from the first try. I had to repeat the process 3 - 5 times in order for the item (that compass) to remain hidden in my inventory after login. However I tried registering with a lot of cracked accounts (sort of simulating what would happen on a public server) and at some point, the player didn't get the compass (it remained hidden). From what I tested, it happens randomly, sometimes the compass is hidden, sometimes is not... I imagine it is pretty hard to determine the cause of what happens since it is quite random... Perhaps you could schedule a task that refreshes player's inventory 1 second after he registers if `ProtectInventoryBeforeLogIn` is set to true... to keep things safe. Or add the possibility to delay the commands themselves.

Looks like in gamemode 1 the items won't reveal if you click them, but if you get an item added to your inventory through /give all the items will be revealed in both gm 0 and gm 1.

**Comment by sgdc3** [comment]
@NewBestX Could you try with latest build again? ;)

**Comment by NewBestX** [comment]
Sorry for the late reply.

Updated to ProtocolLib 4.0.2 and using AuthMe Build #1196

The bug when `ProtectInventoryBeforeLogIn` is set to true is still there. You /register and the items you had in your inventory before remain hidden. This does not happen with /login, perhaps you could check the differences between the way /login handles the restoring inventory part and how /register does...

The bug with changing `ProtectInventoryBeforeLogIn` from true to false and doing /authme reload was fixed. Good job on that :)

**Comment by sgdc3** [comment]
@NewBestX What's your plugin list?

**Comment by NewBestX** [comment]
I had essentialsx, multiverse, worldedit, worldguard, vault and some other small plugins that I made myself (I used that local server to test these plugins). However, I removed everything but AuthMe and ProtocolLib, and still can reproduce the bug.

**Comment by Twonox** [comment]
I've tested. After /register I've again my items.
